#!/bin/bash
# -----------------------------------------------------------------------------
# CloudFront Distribution情報取得リソースファイル(Mac/Linux用)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 【環境変数】
# OS_TYPE         ：OS種別
# OVERWRITE_OPTION：sedコマンドのオプション
# ITEMS           ：セクション数のカウント初期化処理
# ROW_COUNT       ：項目行の行数カウント初期化処理
# AWS_REGION      ：情報を取得するリージョンの指定【編集可】
#                   複数リージョンを取得する場合はカンマ（,）で区切る
# LIST_TMP        ：リージョンリスト作成用tmpファイル
# DISTRIBUTION_TMP：ディストリビューションリスト作成用tmpファイル
# -----------------------------------------------------------------------------
OS_TYPE=$(uname -s)
if [ ${OS_TYPE} == "Darwin" ]; then
  OVERWRITE_OPTION=".tmp"
else
  OVERWRITE_OPTION=""
fi

ITEMS="0"
ROW_COUNT[${ITEMS}]="0"
AWS_REGION="us-east-1"
LIST_TMP=.${RESOURCE_NAME}.tmp
echo ${AWS_REGION} | sed -e "s/ //g" -e "s/,/\n/g" >| ${LIST_TMP}
DISTRIBUTION_TMP=".distribution.tmp"

# -----------------------------------------------------------------------------
# 【メイン処理】
# -----------------------------------------------------------------------------
# タイトル【編集可】
echo "# CloudFront" >| ${OUTPUT_PATH}

# リージョンごとの情報取得
while read REGION_LIST
do
  # リージョンごとの表題【編集可】
  echo "## Distribution (${REGION_LIST})" >> ${OUTPUT_PATH}
  echo "" >> ${OUTPUT_PATH}

  # 項目行の行数カウント処理
  ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

  # リソースリスト取得【編集可】
  aws cloudfront list-distributions --region ${REGION_LIST} | jq -r '.DistributionList.Items[] |
  [
    .Id,
    .Comment,
    .DomainName,
    .Aliases.Items[],
    ([.Origins.Items[].Id] | @csv),
    .Enabled
  ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

  # 項目行とMarkdown形式の表の書式行追加【編集可】
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|ID|説明|ドメイン名|代替ドメイン名|オリジン|ステータス|\n/" ${OUTPUT_PATH}
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

  # 改行【編集可】
  echo "" >> ${OUTPUT_PATH}

  # -----------------------------------------------------------------------------
  # 一般詳細
  # -----------------------------------------------------------------------------
  # ディストリビューションIDのリスト作成
  aws cloudfront list-distributions --region ${REGION_LIST} | jq -r '.DistributionList.Items[].Id' >> ${DISTRIBUTION_TMP}

  while read DISTRIBUTION_ID
  do
    # セクション数変数のインクリメント
    ITEMS=$((${ITEMS}+1))

    # リージョンごとの表題【編集可】
    echo "### ${DISTRIBUTION_ID} 一般詳細 (${REGION_LIST})" >> ${OUTPUT_PATH}
    echo "" >> ${OUTPUT_PATH}

    # 項目行の行数カウント処理
    ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

    # リソースリスト取得【編集可】
    aws cloudfront get-distribution --id ${DISTRIBUTION_ID} --region ${REGION_LIST} | jq -r '
    [
      .Distribution.DomainName, # ディストリビューションドメイン名
      .Distribution.ARN # ARN
    ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

    # 項目行とMarkdown形式の表の書式行追加【編集可】
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|ディストリビューションドメイン名|ARN|\n/" ${OUTPUT_PATH}
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|\n/" ${OUTPUT_PATH}

    # 改行【編集可】
    echo "" >> ${OUTPUT_PATH}

    # -----------------------------------------------------------------------------
    # 一般設定
    # -----------------------------------------------------------------------------
    # セクション数変数のインクリメント
    ITEMS=$((${ITEMS}+1))

    # リージョンごとの表題【編集可】
    echo "### ${DISTRIBUTION_ID} 一般設定 (${REGION_LIST})" >> ${OUTPUT_PATH}
    echo "" >> ${OUTPUT_PATH}

    # 項目行の行数カウント処理
    ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

    # リソースリスト取得【編集可】
    aws cloudfront get-distribution --id ${DISTRIBUTION_ID} --region ${REGION_LIST} | jq -r '
    [
      .Distribution.DistributionConfig.Comment, # 説明
      (.Distribution.DistributionConfig.Aliases.Items[]), # 代替ドメイン名
      .Distribution.DistributionConfig.Logging.Enabled, # 標準ログ記録
      .Distribution.DistributionConfig.Logging.IncludeCookies, # Cookieログ記録
      .Distribution.DistributionConfig.HttpVersion, # HTTPバージョン
      .Distribution.DistributionConfig.ViewerCertificate.MinimumProtocolVersion, # セキュリティポリシー
      (.Distribution.DistributionConfig.WebACLId // "-" | split("/") | .[-2]) # AWS WAF
    ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

    # 項目行とMarkdown形式の表の書式行追加【編集可】
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|説明|代替ドメイン|標準ログ記録|Cookieログ記録|HTTPバージョン|セキュリティポリシー|AWS WAF|\n/" ${OUTPUT_PATH}
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

    # 改行【編集可】
    echo "" >> ${OUTPUT_PATH}

    # -----------------------------------------------------------------------------
    # オリジン
    # -----------------------------------------------------------------------------
    # セクション数変数のインクリメント
    ITEMS=$((${ITEMS}+1))

    # リージョンごとの表題【編集可】
    echo "### ${DISTRIBUTION_ID} オリジン (${REGION_LIST})" >> ${OUTPUT_PATH}
    echo "" >> ${OUTPUT_PATH}

    # 項目行の行数カウント処理
    ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

    # リソースリスト取得【編集可】
    aws cloudfront get-distribution --id ${DISTRIBUTION_ID} --region ${REGION_LIST} | jq -r '.Distribution.DistributionConfig.Origins.Items[] |
    [
      .Id, # オリジン名
      .DomainName, # オリジンドメイン
      .OriginPath // "-", # オリジンパス
      # オリジンタイプ
      (
        if .S3OriginConfig != null then
          "S3"
        else
          "Custom Origin"
        end
      ),
      .OriginShield.OriginShieldRegion // "-", # オリジンシールドリージョン
      .OriginAccessControlId // "-" # オリジンアクセスコントロールID
    ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

    # 項目行とMarkdown形式の表の書式行追加【編集可】
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|オリジン名|オリジンドメイン|オリジンパス|オリジンタイプ|オリジンシールドリージョン|オリジンアクセス|\n/" ${OUTPUT_PATH}
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

    # 改行【編集可】
    echo "" >> ${OUTPUT_PATH}

    # -----------------------------------------------------------------------------
    # ビヘイビア
    # -----------------------------------------------------------------------------
    # セクション数変数のインクリメント
    ITEMS=$((${ITEMS}+1))

    # リージョンごとの表題【編集可】
    echo "### ${DISTRIBUTION_ID} ビヘイビア (${REGION_LIST})" >> ${OUTPUT_PATH}
    echo "" >> ${OUTPUT_PATH}

    # 項目行の行数カウント処理
    ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

    # リソースリスト取得【編集可】
    aws cloudfront get-distribution --id ${DISTRIBUTION_ID} --region ${REGION_LIST} | jq -r '.Distribution.DistributionConfig.CacheBehaviors.Items[] |
    [
      .PathPattern, # パスパターン
      .TargetOriginId, # オリジンまたはオリジングループ
      .ViewerProtocolPolicy, # ビューワープロトコルポリシー
      .CachePolicyId, # キャッシュポリシーID
      .OriginRequestPolicyId // "-" # オリジンリクエストポリシーID
    ] | @tsv' | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

    aws cloudfront get-distribution --id ${DISTRIBUTION_ID} --region ${REGION_LIST} | jq -r '.Distribution.DistributionConfig.DefaultCacheBehavior |
    [
      "default(*)", # パスパターン
      .TargetOriginId, # オリジンまたはオリジングループ
      .ViewerProtocolPolicy, # ビューワープロトコルポリシー
      .CachePolicyId, # キャッシュポリシーID
      .OriginRequestPolicyId // "-" # オリジンリクエストポリシーID
    ] | @tsv' | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

    # 項目行とMarkdown形式の表の書式行追加【編集可】
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|パスパターン|オリジンまたはオリジングループ|ビューワープロトコルポリシー|キャッシュポリシーID|オリジンリクエストポリシーID|\n/" ${OUTPUT_PATH}
    sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

    # 改行【編集可】
    echo "" >> ${OUTPUT_PATH}

  done < ${DISTRIBUTION_TMP}

  # CSVファイルへの変換処理
  if [ ${FILETYPE} == "csv" ]; then
    EXPORT_CSV ${ITEMS} ${OUTPUT_PATH}
  fi

done < ${LIST_TMP}

# 作業用tmpファイルの削除
rm -f ${LIST_TMP}
rm -f ${DISTRIBUTION_TMP}

if [ ${OS_TYPE} == Darwin ]; then
  rm -f ${OUTPUT_PATH}${OVERWRITE_OPTION}
fi