#!/bin/bash
# -----------------------------------------------------------------------------
# RDS情報取得リソースファイル(Mac/Linux用)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 【環境変数】
# OS_TYPE         ：OS種別
# OVERWRITE_OPTION：sedコマンドのオプション
# ITEMS           ：セクション数のカウント初期化処理
# ROW_COUNT       ：項目行の行数カウント初期化処理
# AWS_REGION      ：情報を取得するリージョンの指定【編集可】
#                   複数リージョンを取得する場合はカンマ（,）で区切る
# LIST_TMP        ：リージョンリスト作成用tmpファイル
# -----------------------------------------------------------------------------
OS_TYPE=$(uname -s)
if [ ${OS_TYPE} == "Darwin" ]; then
  OVERWRITE_OPTION=".tmp"
else
  OVERWRITE_OPTION=""
fi

ITEMS="0"
ROW_COUNT[${ITEMS}]="0"
AWS_REGION="ap-northeast-1"
LIST_TMP=.${RESOURCE_NAME}.tmp
echo ${AWS_REGION} | sed -e "s/ //g" -e "s/,/\n/g" >| ${LIST_TMP}

# -----------------------------------------------------------------------------
# 【メイン処理】
# -----------------------------------------------------------------------------
# タイトル【編集可】
echo "# RDS" >| ${OUTPUT_PATH}

# リージョンごとの情報取得
while read REGION_LIST
do
  # リージョンごとの表題【編集可】
  echo "## Aurora Cluster (${REGION_LIST})" >> ${OUTPUT_PATH}
  echo "" >> ${OUTPUT_PATH}

  # 項目行の行数カウント処理
  ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

  # リソースリスト取得【編集可】
  aws rds describe-db-clusters --region ${REGION_LIST} | jq -r '.DBClusters[] |
  [
    .DBClusterIdentifier, # DBクラスタ識別子
    .Engine, # エンジン
    .EngineVersion, # エンジンバージョン
    (.AvailabilityZones | join("<br>")), # リージョンとAZ
    .DBSubnetGroup, # サブネットグループ
    .DBClusterParameterGroup, # パラメータグループ
    (.DBClusterMembers[] | select(.IsClusterWriter == true).DBInstanceIdentifier), # ライターインスタンス
    ([(.DBClusterMembers[] | select(.IsClusterWriter == false).DBInstanceIdentifier)] | join("<br>")), # リーダーインスタンス
    .Endpoint, # ライターエンドポイント
    .ReaderEndpoint # リーダーエンドポイント
  ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

  # 項目行とMarkdown形式の表の書式行追加【編集可】
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|DBクラスタ識別子|エンジン|エンジンバージョン|リージョンとAZ|サブネットグループ|パラメータグループ|ライターインスタンス|リーダーインスタンス|ライターエンドポイント|リーダーエンドポイント|\n/" ${OUTPUT_PATH}
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

  # 改行【編集可】
  echo "" >> ${OUTPUT_PATH}

  # -----------------------------------------------------------------------------
  # Aurora Instance
  # -----------------------------------------------------------------------------
  # セクション数変数のインクリメント
  ITEMS=$((${ITEMS}+1))

  # リージョンごとの表題【編集可】
  echo "## Aurora Instance (${REGION_LIST})" >> ${OUTPUT_PATH}
  echo "" >> ${OUTPUT_PATH}

  # 項目行の行数カウント処理
  ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

  # リソースリスト取得【編集可】
  aws rds describe-db-instances --region ${REGION_LIST} | jq -r '.DBInstances[] |
  [
    .DBClusterIdentifier, # DBクラスタ識別子
    .DBInstanceIdentifier, # DBインスタンス識別子
    .Engine, # エンジン
    .EngineVersion, # エンジンバージョン
    .AvailabilityZone, # リージョンとAZ
    .DBInstanceClass, # サイズ
    .DBSubnetGroup.DBSubnetGroupName, # サブネットグループ
    .DBParameterGroups[].DBParameterGroupName, # パラメータグループ
    .Endpoint.Address # エンドポイント
  ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

  # 項目行とMarkdown形式の表の書式行追加【編集可】
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|DBクラスタ識別子|DBインスタンス識別子|エンジン|エンジンバージョン|リージョンとAZ|サイズ|サブネットグループ|パラメータグループ|エンドポイント|\n/" ${OUTPUT_PATH}
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

  # 改行【編集可】
  echo "" >> ${OUTPUT_PATH}

  # CSVファイルへの変換処理
  if [ ${FILETYPE} == "csv" ]; then
    EXPORT_CSV ${ITEMS} ${OUTPUT_PATH}
  fi

done < ${LIST_TMP}

# 作業用tmpファイルの削除
rm -f ${LIST_TMP}

if [ ${OS_TYPE} == Darwin ]; then
  rm -f ${OUTPUT_PATH}${OVERWRITE_OPTION}
fi