#!/bin/bash
# -----------------------------------------------------------------------------
# SNS情報取得リソースファイル(Mac/Linux用)
# -----------------------------------------------------------------------------
# -----------------------------------------------------------------------------
# 【環境変数】
# OS_TYPE         ：OS種別
# OVERWRITE_OPTION：sedコマンドのオプション
# ITEMS           ：セクション数のカウント初期化処理
# ROW_COUNT       ：項目行の行数カウント初期化処理
# AWS_REGION      ：情報を取得するリージョンの指定【編集可】
#                   複数リージョンを取得する場合はカンマ（,）で区切る
# LIST_TMP        ：リージョンリスト作成用tmpファイル
# -----------------------------------------------------------------------------
OS_TYPE=$(uname -s)
if [ ${OS_TYPE} == "Darwin" ]; then
  OVERWRITE_OPTION=".tmp"
else
  OVERWRITE_OPTION=""
fi

ITEMS="0"
ROW_COUNT[${ITEMS}]="0"
AWS_REGION="ap-northeast-1"
LIST_TMP=.${RESOURCE_NAME}.tmp
echo ${AWS_REGION} | sed -e "s/ //g" -e "s/,/\n/g" >| ${LIST_TMP}

# -----------------------------------------------------------------------------
# トピック
# -----------------------------------------------------------------------------
# タイトル【編集可】
echo "# SNS" >| ${OUTPUT_PATH}

# リージョンごとの情報取得
while read REGION_LIST
do
  # リスト一覧取得用変数の指定【編集可】
  TOPICARN_TMP=".topicarn.tmp"

  # TopicArnのリスト作成【編集可】
  aws sns list-topics --region ${REGION_LIST} | jq -r '.Topics[] | [.TopicArn] | @tsv' | sort >| ${TOPICARN_TMP}

  # リージョンごとの表題【編集可】
  echo "## トピック (${REGION_LIST})" >> ${OUTPUT_PATH}
  echo "" >> ${OUTPUT_PATH}

  # 項目行の行数カウント処理
  ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

  while read TOPICARN_LIST
  do
    # リソースリスト取得【編集可】
    aws sns list-subscriptions-by-topic --topic-arn ${TOPICARN_LIST} --region ${REGION_LIST} | jq -r '.Subscriptions[] |
    [
      (.TopicArn | split(":") | .[-1]), # トピック
      .Owner, # 所有者
      (.SubscriptionArn | split(":") | .[-1]) // "-", # サブスクリプションID
      .Endpoint // "-", # エンドポイント
      .Protocol // "-" # プロトコル
    ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

  done < ${TOPICARN_TMP}

  # 項目行とMarkdown形式の表の書式行追加【編集可】
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|トピック|所有者|サブスクリプションID|エンドポイント|プロトコル|\n/" ${OUTPUT_PATH}
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

  echo "" >> ${OUTPUT_PATH}

  # 作業用tmpファイルの削除
  rm -f ${TOPICARN_TMP}

# -----------------------------------------------------------------------------
# サブスクリプション
# -----------------------------------------------------------------------------
  # リージョンごとの表題【編集可】
  echo "## サブスクリプション (${REGION_LIST})" >> ${OUTPUT_PATH}
  echo "" >> ${OUTPUT_PATH}

  # 項目行の行数カウント処理
  ROW_COUNT[${ITEMS}]=$(wc -l ${OUTPUT_PATH} | awk '{print $1}')

  # リソースリスト取得【編集可】
  aws sns list-subscriptions --region ${REGION_LIST} | jq -r '.Subscriptions[] |
  [
    ((.SubscriptionArn | split(":") | .[-1]) // "-"), # ID
    .Endpoint, # エンドポイント
    .Protocol, # プロトコル
    .Owner, # 所有者
    ((.TopicArn | split(":") | .[-1]) // "-") # トピック
  ] | @tsv' | sort | sed -e "s/\t/|/g" -e "s/^/|/g" -e "s/$/|/g" -e "s/\"//g" >> ${OUTPUT_PATH}

  # 項目行とMarkdown形式の表の書式行追加【編集可】
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+1))s/^/|ID|エンドポイント|プロトコル|所有者|トピック|\n/" ${OUTPUT_PATH}
  sed -i ${OVERWRITE_OPTION} -e "$((${ROW_COUNT[${ITEMS}]}+2))s/^/|:--|:--|:--|:--|:--|\n/" ${OUTPUT_PATH}

  # 改行【編集可】
  echo "" >> ${OUTPUT_PATH}

  # CSVファイルへの変換処理
  if [ ${FILETYPE} == "csv" ]; then
    EXPORT_CSV ${ITEMS} ${OUTPUT_PATH}
  fi

done < ${LIST_TMP}

# 作業用tmpファイルの削除
rm -f ${LIST_TMP}

if [ ${OS_TYPE} == Darwin ]; then
  rm -f ${OUTPUT_PATH}${OVERWRITE_OPTION}
fi